"""Change campaign template_id ondelete from SET_NULL to CASCADE

Revision ID: d5e6fa8cf770
Revises: 16e53094325a
Create Date: 2026-01-27 03:29:38.443486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e6fa8cf770'
down_revision: Union[str, Sequence[str], None] = '16e53094325a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('campaigns_template_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'newsletter_templates', ['template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_template_id_fkey'), 'campaigns', 'newsletter_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
